import type { NextPage } from "next";
import Head from "next/head";
import { useStore } from "../store";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const bears = useStore((state) => state.bears);
  const increaseBearPopulation = useStore((state) => state.increaseBearPopulation);
  const increaseBearCount = () => increaseBearPopulation(1);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>Number of Bears: {bears}</main>
      <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" onClick={() => increaseBearCount()}>Add a Bear</button>
    </div>
  );
};

export default Home;
